### ISSUE TITLE
Order food

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#6]
* [x] confirm snacks budget with Carrie
* [x] get an estimated headcount or cost
* [x] purchase the snacks
* [x] get the snacks to the location

**Comment by ambercabrera** [comment]
It might be easier for me to take on this task. People are weird about buying stuff with city money, in that, our office has one person that has a purchasing card (Karen) and they are the ones that have to purchase the stuff... apparently it's a pain in the ass to do reimbursements because, using the card, we are not charged taxes. If you have an arrangement already set up with Carrie that's cool too, just wanted to check.

**Comment by gotoplanb** [comment]
@ambercabrera Reassigned to you.

**Comment by gotoplanb** [comment]
This was the initial response from Carrie, "Yes, we can certainly support the effort in that way.  It would be good to have a head count by Wednesday, June 1 so that we can place a food order, if needed.  Let me know your sense of what might be appropriate offerings (i.e., sandwiches, healthy snacks, baked goods, tea, water, sodas, other…) and we can talk about the logistics. "

**Comment by ambercabrera** [comment]
The food is in the queue to be ordered and I will bring everything to the event.

**Comment by gotoplanb** [comment]
Hero
